# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: repsy # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: ${{secrets.USER}}
        server-password: ${{secrets.PASS}}  
        overwrite-settings: true

    - name: Version bump for pom.xml
      run: mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion} versions:commit --file pom.xml

    - name: Update versions for latest libraries
      run: |
          echo "GIT_TAG=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo "$(cat /home/runner/.m2/settings.xml)"
    - name: Build with Maven
      run: mvn -B package --file pom.xml --settings /home/runner/.m2/settings.xml

    - name: Deploy to GitHub
      run: mvn -e -X --settings /home/runner/.m2/settings.xml deploy 
    - name: Commit files
      run: |
        git config --local user.email "revision-updater@gamedoora.com"
        git config --local user.name "Version Upgrader"
        git commit -m "Version upgrade" -a
        echo "TAG = $GIT_TAG"
        git tag "$GIT_TAG"
        git push origin master
        git push origin "$GIT_TAG"

